### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by lymanlai** [sahat/megaboilerplate#1]
Is this a new "hackathon starter" for react?

**Comment by sahat** [comment]
This is a work in progress project that will be able to generate boilerplate kits. It is much bigger in scope than hackathon starter. The main issue with hackathon starter is the choices have already been picked for you: 1) jade template engine 2) express framework 3) no client-side framework like angular / react 4) no gulp/webpack build system 5) bootstrap css framework. It's great for what it does - being very simple and easy to get started, but does not offer much flexibility of choices.

There is still plenty to do and things to figure out so I don't think it will be ready any time soon yet. But the idea is similar to Bootstrap's customizer (https://getbootstrap.com/customize/) where you can pick and choose Bootstrap's parts that you need, except in this case you are picking and choosing parts of your boilerplate project - framework, database, template engine, css preprocessor, build tool, optional client-side framework, etc.

**Comment by sahat** [comment]
I was reading my comment above, then looked at the posted date...holy crap, time flies so quickly. It has been 6 months since I started prototyping Mega Boilerplate. Little by little every day I was able to finally complete the project. Going to do some QA, then hopefully announce it on Wednesday.
