### ISSUE TITLE
Support for realtime database with RethinkDB

### ISSUE THREAD

**Issue by SharadKumar** [sahat/megaboilerplate#100]
Consider using Horizon: http://horizon.io/docs/getting-started/

**Comment by sahat** [comment]
IMHO too specialized and too new. Just from the amount of work it requires, adding a new CSS framework and a new server-side framework would take the most time, assuming I am not restricting it to just one particular choice, all permutations must be considered.

As for RethinkDB database, initially I was planning to add it, but that too would require reimplementing several dozen files to use RethinkDB ORM, similar to what I've done with SQL and MongoDB - very time consuming.
