### ISSUE TITLE
Fix responsive login container in Bootstrap demo

### ISSUE THREAD

**Issue by sahat** [sahat/megaboilerplate#106]
Because `.login-container` has a fixed width it looks broken while the rest of the layout is nice and responsive on mobile devices.

Should be a simple CSS fix.

Relevant files:

- https://github.com/sahat/megaboilerplate/blob/master/generators/css-framework/modules/bootstrap/main.css
- https://github.com/sahat/megaboilerplate/blob/master/generators/css-framework/modules/bootstrap/main.less
- https://github.com/sahat/megaboilerplate/blob/master/generators/css-framework/modules/bootstrap/main.scss

---

![2016-06-09 12 03 02](https://cloud.githubusercontent.com/assets/544954/15939333/453d52d4-2e45-11e6-92a6-dec213c39c37.png)

**Comment by estevanmaito** [comment]
I've found that adding `.container` to `.login-container` div and putting `max-width` instead of `width` in  `.login-container` solved the problem (in login and signup views).

Will PR soon.
