### ISSUE TITLE
Google sign-in button not honoring .env settings

### ISSUE THREAD

**Issue by execat** [sahat/megaboilerplate#107]
**Configuration**:

- Platform: Node.js
- Framework: Express
- Database: SQLite
- Template engine: Jade
- CSS framework: Bootstrap

For those settings, creating the `.env` file as stated in the `README.md` works for Facebook and Twitter signins, but Google signup still takes me to the Megaboilerplate authorization rather than my Google app's auth. Removing the `clientId` in `googleLogin()` (line 52 on my `app/actions/oauth.js`) fixes this.

Can anyone confirm that this is happening with them too? Am I doing something wrong?

**Comment by sahat** [comment]
@execat You will need to update Client ID in `oauth.js` with your own. The only time when you can specify both Client ID and Client Secret in `.env` is when you are not using AngularJS or React, i.e. authenticating using Passport.js.

**Comment by sahat** [comment]
I need to make a note in README about this. Those instructions were taken straight from Hackathon Starter which uses Passport.

**Comment by sahat** [comment]
Fixed in 3b4e11359fa787576021dc74d4ccfff8fa843617.
