### ISSUE TITLE
John Papa Styleguide in AngularJS app

### ISSUE THREAD

**Issue by fccoelho7** [sahat/megaboilerplate#109]
John Papa has a great style guide for AngularJS, with nice practices to write a better NG app. So many people use his pattern. It's an idea implement it on your boilerplate. I can contribute rebuilding the code.

More infos:   [https://github.com/johnpapa/angular-styleguide/tree/master/a1](https://github.com/johnpapa/angular-styleguide/tree/master/a1)

**Comment by sahat** [comment]
@fccoelho7 I have seen that style guide. Anything specific in mind or were you referring to the project directory structure?

**Comment by fccoelho7** [comment]
I'm referring to Angular codes and file names. An example is use `var vm = this` instead of `$scope`. Actually this is the main pattern when you think in AngularJS development. This will add a lot!

**Comment by sahat** [comment]
If that's the pattern that people use these days then let's go with it. Last time I have used AngularJS was in 2014, so I am a bit outdated on today's best practices.

If you have time I would appreciate a PR, while I finish up Mocha tests for Angular. Use the style guide but try to keep it simple.

**Comment by fccoelho7** [comment]
I'm glad to help this amazing project. Tomorrow I'll start to change codes and when ready I do some pull requests. :D

**Comment by eduardogch** [comment]
I would be happy to help in this effort @fccoelho7

**Comment by fccoelho7** [comment]
@eduardogch sounds good! Let's maintain contact to do a better way. How can I contact you?

**Comment by eduardogch** [comment]
Invite in google hangout sent @fccoelho7

**Comment by zakarya** [comment]
@fccoelho7 I'd like to help in this effort if there's work left.

**Comment by sahat** [comment]
Any updates on the style guide changes?

**Comment by eduardogch** [comment]
Yes @sahat, check this branch https://github.com/eduardogch/megaboilerplate/tree/refactor-angular

My next goals for this refactor are:

- Reduce using $scope to binding data with controllers and HTML using alias
- Create one Login controller instead to have multiples controllers
- Change factories into services for my peace of mind
- Using alias in the HTML according with the controllers
- Create ng-components (Angular 1.5) for every feature (Login, Account, Contact)

Any help is always welcome!

**Comment by sahat** [comment]
Thanks @eduardogch @fccoelho7! 🎉
