### ISSUE TITLE
Update Express filename conventions

### ISSUE THREAD

**Issue by sahat** [sahat/megaboilerplate#112]
1. Capitalize model filename `user.js` to `User.js`.
2. Change Pascal Case to Camel Case for **all** controller references. For example:
 - Pascal Case: `var UserController = require('./controllers/user')`
 - Camel Case:  `var userController = require('./controllers/user')` (use this)

@niallobrien I have decided to keep controller names as-is for now. At least with model names capitalized, it shouldn't cause any confusion between user model and user controller file names.

**Comment by niallobrien** [comment]
Shame, I think the file name should match the var name. :(
