### ISSUE TITLE
Add Metalsmith (Static Site Generator) to Megaboilerplate

### ISSUE THREAD

**Issue by bnb** [sahat/megaboilerplate#113]
I would be happy to help implement this, as I would use it a lot. I do even have my own boilerplate that I've been working on for Metalsmith for a bit, although it would be amazing to do a build with different plugins ([lots of options](http://www.metalsmith.io/), I'd be happy to categorize them and place them appropriately).

I would also be willing to scaffold out different site functionality, like a blog (already have this working) or whatever else.

**Comment by sahat** [comment]
Sure, would love to see this. The way I did JS Library generator is first by building a fully-featured example, then break it apart into optional features like Travis CI, code coverage, license type.

I assume some of the options would follow that patterns, while other options would be orthogonal to each other, and those usually take a little longer to implement from my experience.

Let me know if you have any questions. But to give you a brief idea of how generators work:

1. All generators are categorized by type.
2. Each generator contains `modules` directory.
3. When you call `await getModule()` you give it a file path starting with the generator type, but excluding `modules` directory, e,g `static-site/metalsmith/index.js`.
4. To "create a new file", you use lodash's set function. Essentially you are creating a big JavaScript object, where object nesting translates into directory structure.
5. All files are created on `params.build` object.
6. You call `replaceCodeMemory` on files inside `params.build` that you have assigned in Step 4. Each file is a Node `Buffer`.

**Comment by bnb** [comment]
@sahat Hey! I'd like to try to work on this today. Got one question: would you be able to explain the .gitkeep file with the Jekyll and Middleman examples? Is that something native to the SSGs or to the Mega Boilerplate project?

**Comment by sahat** [comment]
Ah those are just hacks. There used to be images in there which I removed but wanted to keep folder around. The reason because images were getting corrupted when I create a zip archive. The issue has long be resolved, so you can feel free to use any binary data in the generator.

**Comment by sahat** [comment]
@bnb How is the progress coming along with Metalsmith?

**Comment by bnb** [comment]
@sahat: Hey! So I've actually been re-evaluating Metalsmith recently for some other projects, and I've come to realize it's probably not good to continue using it, nor add it to a project such as megaboilerate. 

There are 7 deps that are _severely_ out of date in the Metalsmith project. The last commit was ~2 months ago, and the community and project hasn't been growing. 

Adding it to Megaboilerate would add support for a stale project that would either be painfully maintained or ignored and neglected in the future. 

Apologies for the trouble!

**Comment by sahat** [comment]
@bnb No worries, I agree with you. Thanks for the follow up.
