### ISSUE TITLE
Foundation CSS top bar responsive issue in demo #2

### ISSUE THREAD

**Issue by sahat** [sahat/megaboilerplate#115]
See attached screenshot.

![menu-issue](https://cloud.githubusercontent.com/assets/544954/15987291/77588074-2ff1-11e6-9291-f1c08cca0ebc.png)

**Comment by badraufran** [comment]
I have experience with using Foundation 6 and developing a responsive menu. I know the fix, but there are a few ways you can display the menu items.

Do you want them to be left justified or centered?

![left justified menu](https://cloud.githubusercontent.com/assets/8602276/15988580/32ca3b14-30aa-11e6-95cb-29f297a46d54.jpg)
![centered menu](https://cloud.githubusercontent.com/assets/8602276/15988581/35fe4f28-30aa-11e6-875b-fd44164e3664.jpg)

I personally prefer left justified, it's easier to read.

**Comment by sahat** [comment]
Left justified would be great.

**Comment by badraufran** [comment]
So I've fixed the menu layout. I know how to fix the responsive menu toggle as well. However, I'm not sure where to implement it.

Basically, Foundation requires you to initialize the Foundation JS for components that need JavaScript. The responsive menu needs JavaScript and wont work unless it's been initialized.

This is an easy fix for the compiled projects (with no JS framework) where you can just include it in the main.js file:

> $(function() {
> 
>   // Your custom JavaScript goes here
> 
>  // Initialize Foundation in here
> });

But I don't know how this would be implemented in the generators. Where should I do this? At the moment I'm adding it in each generateJsFramework[FRAMEWORK].js file.

So at the moment, for generateJsFrameworkNone.js I've added:
> // Add Foundation initialization to main-with-jquery.js
> if (params.cssFramework.includes('foundation')) {
> // Code to add initialization into main-with-jquery.js
> }

Would I use this?
> await replaceCodeMemory(params, 'js-framework/none/main-with-jquery.js', 'NAME_OF_VARIABLE_TO_REPLACE', [Initialization code here]);
And then put the variable in the main-with-jquery.js file.

That's just for the 'None' JS framework option. Not sure where I would put the code in React or AngularJS.

**Comment by sahat** [comment]
@badraufran You can commit the changes and send a PR as is. I can take care of the rest. You are on the right track for "None" JS framework (except invalid `replaceCodeMemory` parameter order), but for AngularJS and React I'll need to see what's the best way to handle it.

**Comment by badraufran** [comment]
@sahat So this is fixed now right? Maybe the demos could be updated. Thanks for finishing the fix.

**Comment by sahat** [comment]
@badraufran Yeah it's fixed, demos will be updated after I migrate them from Azure to OpenShift hosting platform.

**Comment by sahat** [comment]
@badraufran Do you know by any chance how to fix that sticky footer with Foundation CSS?

**Comment by badraufran** [comment]
Not initially, but I haven't looked at it in detail. I'll see if I can help.
