### ISSUE TITLE
Sticky footer overlaying content issue - Demo 2

### ISSUE THREAD

**Issue by badraufran** [sahat/megaboilerplate#116]
In Demo 2, the footer sticks to the bottom of the window regardless of content. It's always stuck at the bottom and overlays content.

On a mobile view, it's fixed to a position where the bottom of the window was when the view was first created. So it will stay there even when scrolling.  

![footer over content - mobile](https://cloud.githubusercontent.com/assets/8602276/15988448/41da1e3a-30a5-11e6-86b2-a05696b176bb.jpg)

On a responsive view, e.g. a resizeable window, the footer will stick to the bottom of the window.

![footer over content - responsive](https://cloud.githubusercontent.com/assets/8602276/15988428/5ce52630-30a4-11e6-90a6-eccf95d79847.jpg)

**Comment by sahat** [comment]
Related #115. I have never used Foundation until this project, so someone with more experience perhaps could help out here.

**Comment by badraufran** [comment]
Would you prefer a JavaScript solution or an HTML and CSS solution?

**Comment by sahat** [comment]
@badraufran CSS solution. It's easily achieved in Bootstrap, don't see why it wouldn't be possible in Foundation. Googling Foundation sticky footer surprisingly returns a lot of JavaScript solutions.

**Comment by badraufran** [comment]
Exactly, it would be really easy to do something in JavaScript, but we shouldn't have to. I think I'm on to something, it's actually really simple. Doing some tests to validate the solution.
