### ISSUE TITLE
Angular password reset link not routed correctly

### ISSUE THREAD

**Issue by paustint** [sahat/megaboilerplate#121]
With the angular boilerplate, there are errors with the password reset functionality.

1. The reset password angular controller calls the Account.forgotPassword() instead of Account.resetPassword()
2. The resetPassword function on the account service tries to call '/reset', but on the server the only valid route is '/reset/:token'

This is not working as it is currently structured and needs to be refactored to call the right function and pass the token from the server to the browser.

In my application I built from this, I ended up taking the password reset as a query param in angular and then passing that to '/reset/:token' on the server because it was easier.

I am happy to make the change, but with the refactor being done with #109, this would make sense to combine with that effort or wait until the refactor is complete.

**Comment by sahat** [comment]
I fixed both issues, however, there seems to be another bug which has been overlooked. When password has been reset successfully it calls Passport's `logIn` function which doesn't apply to React/Angular apps:

```js
user.save(function(err) {
  req.logIn(user, function(err) {
    done(err, user);
  });
});
```
