### ISSUE TITLE
error in the mean bundle

### ISSUE THREAD

**Issue by jffs-aa** [sahat/megaboilerplate#127]
### Configuration
- **Platform:** node
- **Framework**: express
- **Template Engine**: nunjucks
- **CSS Framework**: bootstrap
- **CSS Preprocessor**: css
- **JavaScript Framework**: angularjs
- **Build Tool**: gulp
- **Unit Testing**: jasmine
- **Database**: mongodb
- **Authentication**: email,facebook,google,twitter
- **Deployment**: none

Hi,

I'm running this setting and is giving error in profile update (error: 'Passwords must match')

I noticed that the "NEW PASSWORD" in this view filled
the field "CONFIRM PASSWORD" in view is blank

When I click on "Update Profile" returns the error message "Passwords must match"

This error should not return if I click on "Change Password"?

If I put the password and confirm it updates the same profile, but when I update the page to screen is blank and appears this message on the console ("VM106: 1 Uncaught SyntaxError: Unexpected token u in JSON at position 0")

The same configuration only using react not of any error

Sorry my english google (lol)

Thanks

**Comment by sahat** [comment]
Fixed in 539196069407db9f916746cd0d0ec646b11a6c97 47a1d58fb2ba8a2aacfe6b3513f780b13894e799 96a9fc59da77d6217451b74ef1a9cbd90c2a03ac

**Comment by jffs-aa** [comment]
@sahat It is now available for download on the site?
