### ISSUE TITLE
Add EmberJs to client side frameworks

### ISSUE THREAD

**Issue by eibrahim** [sahat/megaboilerplate#128]
I already mentioned this in the chatroom but I thought I would put it here just to have a record for others.  I assume a similar response to https://github.com/sahat/megaboilerplate/issues/101

**Comment by sahat** [comment]
Hi @eibrahim,

As I have mentioned in Gitter, I would consider adding Ember.js if someone wishes to send a pull request. But I also don't want to keep GitHub issues permanently opened. Let's give it a few weeks, and if there is no interest, I will close it.
