### ISSUE TITLE
Windows issues with MongoDB 

### ISSUE THREAD

**Issue by MobileAppVault** [sahat/megaboilerplate#131]
Hi,

the boilerplate with mongoDB is not running on windows systems.
I am able to login to the web app but after a refresh I got the error "picture is not a property". This comes from the header.js file.

I've tried to find the root cause and I print out the err in server.js

```
  if (req.isAuthenticated()) {
    var payload = req.isAuthenticated();
    User.findById(payload.sub, function(err, user) {
      console.log(err);
      req.user = user;
      next();
    });
  } else {
    next();
  }
```
This give me the following error.

> MongoError "not authorized on test to execute command"

Is there a way to fix this issue?

**Comment by sahat** [comment]
@MobileAppVault Was it a user privilege issue? I have built Mega Boilerplate on Windows 10 machine and never experienced any MongoDB issues you describe, which makes me think it's a problem with user permissions.
