### ISSUE TITLE
server.js error

### ISSUE THREAD

**Issue by furkankinyas** [sahat/megaboilerplate#132]
root@test:~/app# node server.js
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.module.exports.config (/root/app/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/root/app/server.js:16:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3 errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
express-session deprecated req.secret; provide secret option server.js:46:9
Express server listening on port 3000
MongoDB Connection Error. Please make sure that MongoDB is running.

**Comment by sahat** [comment]
Hey, I would need more context here. Is this on your local machine or deployed on a remote server?

**Comment by furkankinyas** [comment]
i use remove server digital ocean ubuntu 14 and installed node.js, git and mongodb 

full text terminal

root@test:~# cd app
root@test:~/app# npm install
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> node-sass@3.7.0 install /root/app/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /root/app/node_modules/node-sass/vendor/linux-x64-48/binding.node

> node-sass@3.7.0 postinstall /root/app/node_modules/node-sass
> node scripts/build.js

"/root/app/node_modules/node-sass/vendor/linux-x64-48/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
delicate-leaf@1.0.0 /root/app
├── async@1.5.2 
├── bcrypt-nodejs@0.0.3 
├─┬ body-parser@1.15.1 
│ ├── bytes@2.3.0 
│ ├── content-type@1.0.2 
│ ├── debug@2.2.0 
│ ├── depd@1.1.0 
│ ├─┬ http-errors@1.4.0 
│ │ ├── inherits@2.0.1 
│ │ └── statuses@1.3.0 
│ ├── iconv-lite@0.4.13 
│ ├─┬ on-finished@2.3.0 
│ │ └── ee-first@1.1.1 
│ ├── qs@6.1.0 
│ ├─┬ raw-body@2.1.6 
│ │ └── unpipe@1.0.0 
│ └─┬ type-is@1.6.13 
│   ├── media-typer@0.3.0 
│   └── mime-types@2.1.11 
├─┬ compression@1.6.2 
│ ├─┬ accepts@1.3.3 
│ │ └── negotiator@0.6.1 
│ ├─┬ compressible@2.0.8 
│ │ └── mime-db@1.23.0 
│ ├── on-headers@1.0.1 
│ └── vary@1.1.0 
├── dotenv@2.0.0 
├─┬ express@4.14.0 
│ ├── array-flatten@1.1.1 
│ ├── content-disposition@0.5.1 
│ ├── cookie@0.3.1 
│ ├── cookie-signature@1.0.6 
│ ├── encodeurl@1.0.1 
│ ├── escape-html@1.0.3 
│ ├── etag@1.7.0 
│ ├── finalhandler@0.5.0 
│ ├── fresh@0.3.0 
│ ├── merge-descriptors@1.0.1 
│ ├── methods@1.1.2 
│ ├── parseurl@1.3.1 
│ ├── path-to-regexp@0.1.7 
│ ├─┬ proxy-addr@1.1.2 
│ │ ├── forwarded@0.1.0 
│ │ └── ipaddr.js@1.1.1 
│ ├── qs@6.2.0 
│ ├── range-parser@1.2.0 
│ ├─┬ send@0.14.1 
│ │ ├── destroy@1.0.4 
│ │ ├─┬ http-errors@1.5.0 
│ │ │ └── setprototypeof@1.0.1 
│ │ └── mime@1.3.4 
│ ├── serve-static@1.11.1 
│ └── utils-merge@1.0.0 
├─┬ express-flash@0.0.2 
│ └── connect-flash@0.1.1 
├─┬ express-session@1.13.0 
│ ├── cookie@0.2.3 
│ ├── crc@3.4.0 
│ └─┬ uid-safe@2.0.0 
│   └── base64-url@1.2.1 
├─┬ express-validator@2.20.5 
│ ├── bluebird@3.3.5 
│ ├── lodash@4.6.1 
│ └── validator@5.2.0 
├─┬ jade@1.11.0 
│ ├── character-parser@1.2.1 
│ ├─┬ clean-css@3.4.18 
│ │ ├─┬ commander@2.8.1 
│ │ │ └── graceful-readlink@1.0.1 
│ │ └─┬ source-map@0.4.4 
│ │   └── amdefine@1.0.0 
│ ├── commander@2.6.0 
│ ├─┬ constantinople@3.0.2 
│ │ └── acorn@2.7.0 
│ ├─┬ jstransformer@0.0.2 
│ │ ├── is-promise@2.1.0 
│ │ └─┬ promise@6.1.0 
│ │   └── asap@1.0.0 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├─┬ transformers@2.1.0 
│ │ ├─┬ css@1.0.8 
│ │ │ ├── css-parse@1.0.4 
│ │ │ └── css-stringify@1.0.5 
│ │ ├─┬ promise@2.0.0 
│ │ │ └── is-promise@1.0.1 
│ │ └─┬ uglify-js@2.2.5 
│ │   ├─┬ optimist@0.3.7 
│ │   │ └── wordwrap@0.0.3 
│ │   └── source-map@0.1.43 
│ ├─┬ uglify-js@2.6.2 
│ │ ├── async@0.2.10 
│ │ ├── source-map@0.5.6 
│ │ ├── uglify-to-browserify@1.0.2 
│ │ └─┬ yargs@3.10.0 
│ │   ├── camelcase@1.2.1 
│ │   ├─┬ cliui@2.1.0 
│ │   │ ├─┬ center-align@0.1.3 
│ │   │ │ ├─┬ align-text@0.1.4 
│ │   │ │ │ ├─┬ kind-of@3.0.3 
│ │   │ │ │ │ └── is-buffer@1.1.3 
│ │   │ │ │ ├── longest@1.0.1 
│ │   │ │ │ └── repeat-string@1.5.4 
│ │   │ │ └── lazy-cache@1.0.4 
│ │   │ ├── right-align@0.1.3 
│ │   │ └── wordwrap@0.0.2 
│ │   ├── decamelize@1.2.0 
│ │   └── window-size@0.1.0 
│ ├── void-elements@2.0.1 
│ └─┬ with@4.0.3 
│   ├── acorn@1.2.2 
│   └── acorn-globals@1.0.9 
├── method-override@2.3.6 
├─┬ mongoose@4.5.0 
│ ├── bson@0.4.23 
│ ├── hooks-fixed@1.1.0 
│ ├── kareem@1.1.0 
│ ├─┬ mongodb@2.1.18 
│ │ ├── es6-promise@3.0.2 
│ │ ├─┬ mongodb-core@1.3.18 
│ │ │ └─┬ require_optional@1.0.0 
│ │ │   └── resolve-from@2.0.0 
│ │ └─┬ readable-stream@1.0.31 
│ │   ├── core-util-is@1.0.2 
│ │   └── string_decoder@0.10.31 
│ ├── mpath@0.2.1 
│ ├── mpromise@0.5.5 
│ ├─┬ mquery@1.11.0 
│ │ ├── bluebird@2.10.2 
│ │ └── sliced@0.0.5 
│ ├── ms@0.7.1 
│ ├── muri@1.1.0 
│ ├── regexp-clone@0.0.1 
│ └── sliced@1.0.1 
├─┬ morgan@1.7.0 
│ └── basic-auth@1.0.4 
├─┬ node-sass-middleware@0.9.8 
│ └─┬ node-sass@3.7.0 
│   ├── async-foreach@0.1.3 
│   ├─┬ chalk@1.1.3 
│   │ ├── ansi-styles@2.2.1 
│   │ ├── escape-string-regexp@1.0.5 
│   │ ├─┬ has-ansi@2.0.0 
│   │ │ └── ansi-regex@2.0.0 
│   │ ├── strip-ansi@3.0.1 
│   │ └── supports-color@2.0.0 
│   ├─┬ cross-spawn-async@2.2.4 
│   │ ├─┬ lru-cache@4.0.1 
│   │ │ ├── pseudomap@1.0.2 
│   │ │ └── yallist@2.0.0 
│   │ └─┬ which@1.2.10 
│   │   └── isexe@1.1.2 
│   ├─┬ gaze@1.0.0 
│   │ └─┬ globule@0.2.0 
│   │   ├─┬ glob@3.2.11 
│   │   │ └─┬ minimatch@0.3.0 
│   │   │   └── lru-cache@2.7.3 
│   │   ├── lodash@2.4.2 
│   │   └─┬ minimatch@0.2.14 
│   │     └── lru-cache@2.7.3 
│   ├── get-stdin@4.0.1 
│   ├─┬ glob@7.0.4 
│   │ ├── fs.realpath@1.0.0 
│   │ ├─┬ inflight@1.0.5 
│   │ │ └── wrappy@1.0.2 
│   │ ├─┬ minimatch@3.0.0 
│   │ │ └─┬ brace-expansion@1.1.5 
│   │ │   ├── balanced-match@0.4.1 
│   │ │   └── concat-map@0.0.1 
│   │ ├── once@1.3.3 
│   │ └── path-is-absolute@1.0.0 
│   ├── in-publish@2.0.0 
│   ├─┬ meow@3.7.0 
│   │ ├─┬ camelcase-keys@2.1.0 
│   │ │ └── camelcase@2.1.1 
│   │ ├─┬ loud-rejection@1.5.0 
│   │ │ ├─┬ currently-unhandled@0.4.1 
│   │ │ │ └── array-find-index@1.0.1 
│   │ │ └── signal-exit@3.0.0 
│   │ ├── map-obj@1.0.1 
│   │ ├── minimist@1.2.0 
│   │ ├─┬ normalize-package-data@2.3.5 
│   │ │ ├── hosted-git-info@2.1.5 
│   │ │ ├─┬ is-builtin-module@1.0.0 
│   │ │ │ └── builtin-modules@1.1.1 
│   │ │ └─┬ validate-npm-package-license@3.0.1 
│   │ │   ├─┬ spdx-correct@1.0.2 
│   │ │   │ └── spdx-license-ids@1.2.1 
│   │ │   └─┬ spdx-expression-parse@1.0.2 
│   │ │     └── spdx-exceptions@1.0.4 
│   │ ├── object-assign@4.1.0 
│   │ ├─┬ read-pkg-up@1.0.1 
│   │ │ ├─┬ find-up@1.1.2 
│   │ │ │ └── path-exists@2.1.0 
│   │ │ └─┬ read-pkg@1.1.0 
│   │ │   ├─┬ load-json-file@1.1.0 
│   │ │   │ ├─┬ parse-json@2.2.0 
│   │ │   │ │ └─┬ error-ex@1.3.0 
│   │ │   │ │   └── is-arrayish@0.2.1 
│   │ │   │ ├── pify@2.3.0 
│   │ │   │ └─┬ strip-bom@2.0.0 
│   │ │   │   └── is-utf8@0.2.1 
│   │ │   └── path-type@1.1.0 
│   │ ├─┬ redent@1.0.0 
│   │ │ ├─┬ indent-string@2.1.0 
│   │ │ │ └─┬ repeating@2.0.1 
│   │ │ │   └── is-finite@1.0.1 
│   │ │ └── strip-indent@1.0.1 
│   │ └── trim-newlines@1.0.0 
│   ├── nan@2.3.5 
│   ├─┬ node-gyp@3.3.1 
│   │ ├── fstream@1.0.9 
│   │ ├─┬ glob@4.5.3 
│   │ │ └── minimatch@2.0.10 
│   │ ├── graceful-fs@4.1.4 
│   │ ├─┬ minimatch@1.0.0 
│   │ │ ├── lru-cache@2.7.3 
│   │ │ └── sigmund@1.0.1 
│   │ ├─┬ nopt@3.0.6 
│   │ │ └── abbrev@1.0.9 
│   │ ├─┬ npmlog@2.0.4 
│   │ │ ├── ansi@0.3.1 
│   │ │ ├─┬ are-we-there-yet@1.1.2 
│   │ │ │ ├── delegates@1.0.0 
│   │ │ │ └─┬ readable-stream@2.1.4 
│   │ │ │   ├── buffer-shims@1.0.0 
│   │ │ │   └── isarray@1.0.0 
│   │ │ └─┬ gauge@1.2.7 
│   │ │   ├── has-unicode@2.0.0 
│   │ │   ├─┬ lodash.pad@4.4.0 
│   │ │   │ ├── lodash._baseslice@4.0.0 
│   │ │   │ ├── lodash._basetostring@4.12.0 
│   │ │   │ └── lodash.tostring@4.1.3 
│   │ │   ├── lodash.padend@4.5.0 
│   │ │   └── lodash.padstart@4.5.0 
│   │ ├─┬ osenv@0.1.3 
│   │ │ ├── os-homedir@1.0.1 
│   │ │ └── os-tmpdir@1.0.1 
│   │ ├─┬ path-array@1.0.1 
│   │ │ └─┬ array-index@1.0.0 
│   │ │   └─┬ es6-symbol@3.1.0 
│   │ │     ├── d@0.1.1 
│   │ │     └─┬ es5-ext@0.10.11 
│   │ │       ├── es6-iterator@2.0.0 
│   │ │       └── es6-symbol@3.0.2 
│   │ ├── rimraf@2.5.2 
│   │ ├── semver@5.1.0 
│   │ └─┬ tar@2.2.1 
│   │   └── block-stream@0.0.9 
│   ├─┬ request@2.72.0 
│   │ ├── aws-sign2@0.6.0 
│   │ ├── aws4@1.4.1 
│   │ ├─┬ bl@1.1.2 
│   │ │ └─┬ readable-stream@2.0.6 
│   │ │   ├── isarray@1.0.0 
│   │ │   ├── process-nextick-args@1.0.7 
│   │ │   └── util-deprecate@1.0.2 
│   │ ├── caseless@0.11.0 
│   │ ├─┬ combined-stream@1.0.5 
│   │ │ └── delayed-stream@1.0.0 
│   │ ├── extend@3.0.0 
│   │ ├── forever-agent@0.6.1 
│   │ ├── form-data@1.0.0-rc4 
│   │ ├─┬ har-validator@2.0.6 
│   │ │ ├── commander@2.9.0 
│   │ │ ├─┬ is-my-json-valid@2.13.1 
│   │ │ │ ├── generate-function@2.0.0 
│   │ │ │ ├─┬ generate-object-property@1.2.0 
│   │ │ │ │ └── is-property@1.0.2 
│   │ │ │ ├── jsonpointer@2.0.0 
│   │ │ │ └── xtend@4.0.1 
│   │ │ └─┬ pinkie-promise@2.0.1 
│   │ │   └── pinkie@2.0.4 
│   │ ├─┬ hawk@3.1.3 
│   │ │ ├── boom@2.10.1 
│   │ │ ├── cryptiles@2.0.5 
│   │ │ ├── hoek@2.16.3 
│   │ │ └── sntp@1.0.9 
│   │ ├─┬ http-signature@1.1.1 
│   │ │ ├── assert-plus@0.2.0 
│   │ │ ├─┬ jsprim@1.2.2 
│   │ │ │ ├── extsprintf@1.0.2 
│   │ │ │ ├── json-schema@0.2.2 
│   │ │ │ └── verror@1.3.6 
│   │ │ └─┬ sshpk@1.8.3 
│   │ │   ├── asn1@0.2.3 
│   │ │   ├── assert-plus@1.0.0 
│   │ │   ├─┬ dashdash@1.14.0 
│   │ │   │ └── assert-plus@1.0.0 
│   │ │   ├── ecc-jsbn@0.1.1 
│   │ │   ├─┬ getpass@0.1.6 
│   │ │   │ └── assert-plus@1.0.0 
│   │ │   ├── jodid25519@1.0.2 
│   │ │   ├── jsbn@0.1.0 
│   │ │   └── tweetnacl@0.13.3 
│   │ ├── is-typedarray@1.0.0 
│   │ ├── isstream@0.1.2 
│   │ ├── json-stringify-safe@5.0.1 
│   │ ├── node-uuid@1.4.7 
│   │ ├── oauth-sign@0.8.2 
│   │ ├── stringstream@0.0.5 
│   │ ├── tough-cookie@2.2.2 
│   │ └── tunnel-agent@0.4.3 
│   └─┬ sass-graph@2.1.2 
│     └─┬ yargs@4.7.1 
│       ├── camelcase@3.0.0 
│       ├─┬ cliui@3.2.0 
│       │ └── wrap-ansi@2.0.0 
│       ├─┬ lodash.assign@4.0.9 
│       │ ├── lodash.keys@4.0.7 
│       │ └── lodash.rest@4.0.3 
│       ├─┬ os-locale@1.4.0 
│       │ └─┬ lcid@1.0.0 
│       │   └── invert-kv@1.0.0 
│       ├─┬ pkg-conf@1.1.3 
│       │ └── symbol@0.2.3 
│       ├── require-main-filename@1.0.1 
│       ├── set-blocking@1.0.0 
│       ├─┬ string-width@1.0.1 
│       │ ├─┬ code-point-at@1.0.0 
│       │ │ └── number-is-nan@1.0.0 
│       │ └── is-fullwidth-code-point@1.0.0 
│       ├── window-size@0.2.0 
│       ├── y18n@3.2.1 
│       └─┬ yargs-parser@2.4.0 
│         └── camelcase@2.1.1 
├─┬ nodemailer@2.4.2 
│ ├─┬ libmime@2.0.3 
│ │ ├── libbase64@0.1.0 
│ │ └── libqp@1.1.0 
│ ├─┬ mailcomposer@3.9.0 
│ │ └─┬ buildmail@3.7.0 
│ │   └── addressparser@1.0.1 
│ ├─┬ nodemailer-direct-transport@3.1.0 
│ │ └─┬ smtp-connection@2.5.0 
│ │   └─┬ httpntlm@1.6.1 
│ │     ├── httpreq@0.4.22 
│ │     └── underscore@1.7.0 
│ ├─┬ nodemailer-shared@1.0.5 
│ │ └── nodemailer-fetch@1.4.0 
│ ├─┬ nodemailer-smtp-pool@2.6.0 
│ │ └── nodemailer-wellknown@0.1.9 
│ ├── nodemailer-smtp-transport@2.5.0 
│ └─┬ socks@1.1.9 
│   ├── ip@1.1.3 
│   └── smart-buffer@1.0.11 
├─┬ passport@0.3.2 
│ ├── passport-strategy@1.0.0 
│ └── pause@0.0.1 
├── passport-local@1.0.0 
└─┬ socket.io@1.4.6 
  ├─┬ engine.io@1.6.9 
  │ ├─┬ accepts@1.1.4 
  │ │ ├─┬ mime-types@2.0.14 
  │ │ │ └── mime-db@1.12.0 
  │ │ └── negotiator@0.4.9 
  │ ├── base64id@0.1.0 
  │ ├─┬ engine.io-parser@1.2.4 
  │ │ ├── after@0.8.1 
  │ │ ├── arraybuffer.slice@0.0.6 
  │ │ ├── base64-arraybuffer@0.1.2 
  │ │ ├── blob@0.0.4 
  │ │ ├── has-binary@0.1.6 
  │ │ └── utf8@2.1.0 
  │ └─┬ ws@1.0.1 
  │   ├── options@0.0.6 
  │   └── ultron@1.0.2 
  ├─┬ has-binary@0.1.7 
  │ └── isarray@0.0.1 
  ├─┬ socket.io-adapter@0.4.0 
  │ └─┬ socket.io-parser@2.2.2 
  │   ├── debug@0.7.4 
  │   └── json3@3.2.6 
  ├─┬ socket.io-client@1.4.6 
  │ ├── backo2@1.0.2 
  │ ├── component-bind@1.0.0 
  │ ├── component-emitter@1.2.0 
  │ ├─┬ engine.io-client@1.6.9 
  │ │ ├── component-inherit@0.0.3 
  │ │ ├── has-cors@1.1.0 
  │ │ ├── parsejson@0.0.1 
  │ │ ├── parseqs@0.0.2 
  │ │ ├── xmlhttprequest-ssl@1.5.1 
  │ │ └── yeast@0.1.2 
  │ ├── indexof@0.0.1 
  │ ├── object-component@0.0.3 
  │ ├─┬ parseuri@0.0.4 
  │ │ └─┬ better-assert@1.0.2 
  │ │   └── callsite@1.0.0 
  │ └── to-array@0.1.4 
  └─┬ socket.io-parser@2.2.6 
    ├── benchmark@1.0.0 
    ├── component-emitter@1.1.2 
    └── json3@3.3.2 

npm WARN delicate-leaf@1.0.0 No repository field.
npm WARN delicate-leaf@1.0.0 No license field.
root@test:~/app# node server.js
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.module.exports.config (/root/app/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/root/app/server.js:16:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3 errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
express-session deprecated req.secret; provide secret option server.js:46:9
Express server listening on port 3000
MongoDB Connection Error. Please make sure that MongoDB is running.

**Comment by sahat** [comment]
There are a couple of issues here.

1) I can only assume you did not set `NODE_ENV=production` which is why dotenv is complaining about missing file. `.env` is designed for local development only. You can disable that error in `server.js` by passing silent: true flag:

```js
dotenv.load({ silent: true });
```

2) Regardless of step 1, you still have to set environment variables manually. I think in Ubuntu you do 
`export MONGODB=localhost`. You gotta do the same for all other environment variables in your `.env` file you received with megaboilerplate-app.

3) You should write a script to automate all these tasks on Digital Ocean, like setting environment variables. 

4) Also what you can do is remove `.env` from .gitignore and manually add it via `git add .env` `git commit -m 'added .env'`.
