### ISSUE TITLE
Init foundation JS on main layout

### ISSUE THREAD

**Issue by reyhansofian** [sahat/megaboilerplate#136]
Thanks for your great boilerplate! I love it!

There's a small issue with the foundation (I'm using React + Foundation + Handlebars). On your main layout (`views > layouts > main.handlebars`), there's no foundation initialize code that looks like this:

```
<script type="text/javascript">
  $(document).foundation();
</script>
```

Without this code, any foundation javascript won't run. Maybe you can add it by default? Thanks!

**Comment by sahat** [comment]
Hey @reyhansofian, this has been fixed in https://github.com/sahat/megaboilerplate/pull/125.

When you choose React, you will see Foundation initialization insider Header.js component, inside componentDidMount.

**Comment by reyhansofian** [comment]
Ah, sorry I missed that issue. I'll close this then.
