### ISSUE TITLE
Github Login for mega boilerplate

### ISSUE THREAD

**Issue by MichaelGofron** [sahat/megaboilerplate#143]
I’m trying to create github authentication using the starter code for mega boilerplate.

My settings for the project are node.js, express, bootstrap, sass, react, handlebars, web pack, no testing, PSQL, authentication with email Facebook,google,twitter,vk, and heroku.

Is there any sample project people made with Github Login?

**Comment by sahat** [comment]
Looks like it has been resolved in the Gitter chat. Closing the issue.
