### ISSUE TITLE
Add RethinkDB to Database Options

### ISSUE THREAD

**Issue by ajalger** [sahat/megaboilerplate#146]
With the increasing popularity of RethinkDB, it would be nice to use it instead of MongoDB, or other databases, especially for realtime data.

**Comment by sahat** [comment]
Hey @ajalger, while I agree it would be nice to have RethinkDB, it would also require a lot of work - many days to weeks, depending on how comfortable you are with RethinkDB and https://thinky.io, which I am not familiar with at all.

I am going to close this issue, unless someone has time to volunteer for a PR.
