### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by upq** [sahat/megaboilerplate#152]
React.js SASS

Im wondering where is the code responsible for compiling scss file, and minifying the css.

Second question about styles is Im structruing my components along with their scss files, like so

```
Components/
|--Header/
|------ Header.js
|------ Header.scss
```

Im now migrating my code to use it with the megaboilerplate, any suggestions on how to get this done?

**Comment by sahat** [comment]
@upq It's done via node-sass-middleware. If you want to import individual styles into React components, take a look at how this project is doing it. https://github.com/chentsulin/electron-react-boilerplate/tree/master/app/components

**Comment by sahat** [comment]
@upq Could you please close this issue if that answers your question?
