### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by upq** [sahat/megaboilerplate#154]
@sahat 

I believe we should start building a community I highly encourge having a gitter or discord channel were we can discuss small issues rather than bloating the issues tab on github.

And after that we can also discuss what we can do in the future, assign tasks and think about how to improve this work that I believe everyone in the wolrd would need at some point.

**Comment by sahat** [comment]
There is a public Gitter channel alread: https://gitter.im/sahat/megaboilerplate
