### ISSUE TITLE
login/signup page contains social media divider even when only email is selected

### ISSUE THREAD

**Issue by OmgImAlexis** [sahat/megaboilerplate#156]
I selected `Node -> Express -> Bootstrap -> None/CSS -> Angular -> Gulp + Browserify -> Mocha -> MongoDB -> Email -> None`.

![screen shot 2016-07-07 at 2 05 12 pm](https://cloud.githubusercontent.com/assets/6525926/16654096/22c863a2-444c-11e6-9c28-363c1c7b21cd.png)

**Comment by sahat** [comment]
This would be kind of hard to fix because there are so many permutations of CSS Frameworks * Template Engines. It would take hours to fix it in Mega Boilerplate, where it would take a few seconds to remove that line from the generated code.

I am going to keep it as is for now.
