### ISSUE TITLE
Framework flow is wrong

### ISSUE THREAD

**Issue by Randore** [sahat/megaboilerplate#180]
![wrong-flow](https://cloud.githubusercontent.com/assets/443526/18699193/463fe396-7fed-11e6-8394-726dedd3c18d.jpg)

Bootstrap should come under **Bootstrap** section and not under **SASS**

**Comment by Shuyinsama** [comment]
This isn't wrong.
Bootstrap has multiple different repo's one for CSS the other one is for SASS and the last one is for LESS.
So the "Framework Flow Options" are dependent on if you choose Bootstrap "None / CSS", "SASS" or "LESS". (For example if you choose "None / CSS" you have the option to minify, while with "SASS" that is not the case)


I think the flow is correct as it is.

**Comment by Randore** [comment]
ok
