### ISSUE TITLE
knexfile appears twice

### ISSUE THREAD

**Issue by pitanyc** [sahat/megaboilerplate#80]
Seems like knexfile appears both under config/ and in the main directory.

Generated:
node
express
jade
bootstrap
sass
react
gulp
no unit testing
postgreSQL
heroku

You probably meant to replace config/knexfile with the one that got copied into the main directory.

**Comment by sahat** [comment]
Thanks this was a typo error from this commit: 4fc225c5ad25fea455c5db1ec9d701d6db482716

**Comment by pitanyc** [comment]
=)
