### ISSUE TITLE
Add optional JavaScript transpilers 

### ISSUE THREAD

**Issue by KerryRitter** [sahat/megaboilerplate#83]
It'd be awesome to include transpiler options like TypeScript or CoffeeScript.

**Comment by sahat** [comment]
That would be an insane amount of work to add something like that across all generators! 😁 

It would have to be a little more specific. A good candidate for this would be Angular 2 generator with a choice of ES6 or TypeScript.

**Comment by awjreynolds** [comment]
Given Angular 2's typescript focus, I would suggest implementing it for that only to begin with.

**Comment by sahat** [comment]
@awjreynolds That's the plan! Also considering that most of Angular 2 documentation is written in TypeScript at the current time.

**Comment by niallobrien** [comment]
Agreed regarding Typescript but I don't think Coffeescript is a sensible solution any longer, especially with ES6.

**Comment by KerryRitter** [comment]
Fair enough. That's just something keeping me from using the tool so I figured I'd make a suggestion :)

I would agree with CoffeeScript sentiment.

**Comment by sahat** [comment]
Closing this issue. I will keep in mind to add ES6 and TypeScript for Angular 2 generator, but doing it bottom up for every possible combination is not practical.
