### ISSUE TITLE
Please add ejs support

### ISSUE THREAD

**Issue by Gum-Joe** [sahat/megaboilerplate#85]
First of all: well done for making this project (I have been patiently waiting since you suggested it in sahat/hackathon-starter#439)!

I have just been having a look at your live example generator and I would love it if `ejs` support was added.

**Why add ejs?:**

- Still used by lots of JS developers (I think)
- Allows embedding of JS into a page, which (I think) Jade does not. This could used for dynamic content, such as showing something if a property is or is not equal to something
- Might not be as clean as `jade`, but closely resembles normal HTML, which means you do not have to learn a new Markup language to design websites with it.

Thanks in advanced!

**Comment by sahat** [comment]
Hi @Gum-Joe,

Thanks.

I will consider it. This change would require creating a dedicated EJS template engine generator and **58** additional templates which is no small work.

**Comment by Gum-Joe** [comment]
@sahat Sorry, I did not realise would need that much work - you clearly have made no small task here, maintaining this repo.

**Comment by niallobrien** [comment]
I personally think that Nunjucks satisfies the same needs as EJS. Nunjucks is an overall better solution and vote not to add EJS.

**Comment by Gum-Joe** [comment]
@niallobrien Nunjucks looks good, but I just prefer having the `<html>` and `<body` tags in my HTML. Guess everyone programs differently.

**Comment by sahat** [comment]
For what it's worth, here is what people have been selecting in the past few hours:

<img width="625" alt="screen shot 2016-06-08 at 1 40 54 pm" src="https://cloud.githubusercontent.com/assets/544954/15904377/c1fbc3b8-2d7e-11e6-8876-7b7f73045060.png">

**Comment by Gum-Joe** [comment]
Ok. After all, I knew to the programming scene (stated last year) and only know `jade`, `ejs` and `html` as view engines.
