### ISSUE TITLE
Enable Webpack hot module replacement for Redux reducers

### ISSUE THREAD

**Issue by Dracyr** [sahat/megaboilerplate#86]
When using Webpack and React, redux reducers do not keep state during hot reloads.

There is a simple fix though in `app/store/configureStore.js`
```
export default function configureStore(initialState) {
  const store = createStore(
    rootReducer,
    initialState,
    applyMiddleware(thunk)
  );

  // Enable Webpack hot module replacement for reducers
  if (module.hot) {
    module.hot.accept('../reducers', () => {
      const nextRootReducer = require('../reducers');
      store.replaceReducer(nextRootReducer);
    });
  }

  return store;
}
```

Refer to https://github.com/erikras/react-redux-universal-hot-example/issues/44#issuecomment-132260397 for more info.

Great project!

**Comment by niallobrien** [comment]
Can you submit a PR to add it to this project please?

**Comment by sahat** [comment]
Should be a simple change in https://github.com/sahat/megaboilerplate/blob/master/generators/js-framework/modules/react/store/configureStore.js
