### ISSUE TITLE
"lodash" npm module is needed but not specified in package.json

### ISSUE THREAD

**Issue by maephisto** [sahat/megaboilerplate#99]
Here's my app config:
### Configuration
- **Platform:** node
- **Framework**: express
- **Template Engine**: handlebars
- **CSS Framework**: bootstrap
- **CSS Preprocessor**: less
- **JavaScript Framework**: react
- **Build Tool**: gulp
- **Unit Testing**: mocha
- **Database**: mongodb
- **Authentication**: email,facebook,google,twitter
- **Deployment**: heroku

when running the app with "npm start" i got an error, due to the fact the "lodash" was not available. I installed it and then everything was fine.

I see the module is available in "master" but it was not there after download.

**Comment by icebob** [comment]
+1

**Comment by sahat** [comment]
Strangely enough, when I do `npm install`, lodash is installed into node_modules, but it isn't inside package.json.

In any case, there is an unused `var _ = require('lodash')` reference in the User controller which I will remove and the problem should go away.
